import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TransactionProvider } from '@/context/TransactionContext'
import { SideBarProvider } from '@/components/SideBar/SideBarContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <TransactionProvider>
        <SideBarProvider>
          <body className={inter.className}>{children}</body>
        </SideBarProvider>
      </TransactionProvider>
    </html>
  )
}
